# Generated by Django 5.0.6 on 2024-06-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habbits', '0007_alter_habbit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habbit',
            name='update_time',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующей отправки'),
        ),
    ]
